name: Draw keymap

on:
  push:
    paths:
      - 'config/toucan.keymap'
      - 'config/toucan.json'
      - 'keymap_drawer.config.yaml'
      - '.github/workflows/draw-keymap.yml'
  workflow_dispatch:

jobs:
  draw:
    permissions:
      contents: write
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@a44809b8cc718cbff646641f49a8f71a9368336d # v0.23.0
    with:
      keymap_patterns: 'config/toucan.keymap'
      json_path: 'config'
      output_folder: 'keymap-drawer'
      commit_message: 'keymap-drawer: render toucan.svg'
